pipeline {
    agent {
    kubernetes {
      label 'cicdPod'
      defaultContainer 'maven-slave'
      yamlFile 'devops/CicdPod.yaml'
    }
  }

  environment {
           IMAGE_REG = 'localhost:5000'
           IMAGE_REG_NS = 'cicd'
           APP_VERSION = '0.0.1'
           registry = 'localhost:5000'
           registryCredential = 'dockerlogin'
  }
    
    stages {
       stage('check out') {
          steps {
              echo 'checkout source code'
		  }
       }
       
       stage ('build jar') {
          steps {
             container('maven-slave') {
	             echo 'build'
	             sh 'mvn clean package'
	         }
          }
       }
       
        stage ('build image') {
	    environment {
		REGISTRY_HOST = 'http://localhost:5000'
                REGISTRY_CREDS = credentials('myRegistryCredential')
           }
		
          steps {
             container('cicd-docker') {
	             sh 'echo $REGISTRY_CREDS_PSW | docker login -u $REGISTRY_CREDS_USR --password-stdin $REGISTRY_HOST'
		     sh 'skaffold build -f devops/skaffold.yaml'  
	         }
          }
       }
	    
       stage('deploy') {
          steps {
            container('cicd-docker') {
                echo 'deploy'
                sh 'helm ls'
            }
          }
       }
    }
}
