pipeline {
    agent {
    kubernetes {
      label 'cicdPod'
      defaultContainer 'maven-slave'
      yamlFile 'devops/CicdPod.yaml'
    }
  }
    
    stages {
       stage('check out') {
          steps {
              echo 'checkout source code'
		  }
       }
       
       stage ('build jar') {
          steps {
             container('maven-slave') {
	             echo 'build'
	             sh 'mvn clean package'
	         }
          }
       }
       
        stage ('build image') {
          steps {
             container('maven-slave') {
	             echo 'build image'
		     dir('devops') {
	                sh 'skaffold build -f skaffold.yaml'
		     }
	         }
          }
       }
	    
       stage('deploy') {
          steps {
            container('maven-slave') {
                echo 'deploy'
                sh 'helm ls'
            }
          }
       }
    }
}
