apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: citest
    docker:
      dockerfilePath: devops/Dockerfile
 tagPolicy:
    envTemplate:
      template: "{{.IMAGE_REG}}/{{.IMAGE_REG_NS}}/{{.IMAGE_NAME}}:{{.APP_VERSION}}"
