apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_REG}}/{{.IMAGE_REG_NS}}/{{.IMAGE_NAME}}:{{.APP_VERSION}}"
  artifacts:
  - image: citest
    docker:
      dockerfile: "devops/Dockerfile"
deploy:
  helm:
    releases:
    - name: cicd
      chartPath: charts
      setValueTemplates:
        image.repository: "{{.DOCKER_REGISTRY}}/xinyuwang2018/cicd"
        image.tag: "{{.DIGEST_HEX}}"
